[package]
name = "frame-analyzer-ebpf"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya = "0.12"
aya-log = "0.2"
frame-analyzer-ebpf-common = { path = "../frame-analyzer-ebpf-common", features = ["user"] }
anyhow = "1"
libc = "0.2"
lazy_static = "1.4.0"
