[package]
name = "simple-analyzer"
version = "0.1.0"
edition = "2021"
package = false

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
ctrlc = "3.4.4"
frame-analyzer = { path = "../../frame-analyzer" }
